kind: ServiceAccount
apiVersion: v1
metadata:
  name: efs-csi-node-sa
  namespace: kube-system
  selfLink: /api/v1/namespaces/kube-system/serviceaccounts/efs-csi-node-sa
  # uid: 547e1b78-7147-405b-88c4-11986350aa9e
  # resourceVersion: '91125'
  # creationTimestamp: '2021-07-16T10:07:49Z'
  labels:
    app.kubernetes.io/name: aws-efs-csi-driver
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"aws-efs-csi-driver"},"name":"efs-csi-node-sa","namespace":"kube-system"}}
  managedFields:
    - manager: kube-controller-manager
      # operation: Update
      apiVersion: v1
      # time: '2021-07-16T10:07:49Z'
      # fieldsType: FieldsV1
      # fieldsV1:
      #   'f:secrets':
      #     .: {}
      #     'k:{"name":"ebs-csi-node-sa-token-zmnrl"}':
      #       .: {}
      #       'f:name': {}
    # - manager: kubectl-client-side-apply
    #   operation: Update
    #   apiVersion: v1
    #   time: '2021-07-16T10:07:49Z'
    #   fieldsType: FieldsV1
    #   fieldsV1:
    #     'f:metadata':
    #       'f:annotations':
    #         .: {}
    #         'f:kubectl.kubernetes.io/last-applied-configuration': {}
    #       'f:labels':
    #         .: {}
    #         'f:app.kubernetes.io/name': {}
secrets:
  - name: efs-csi-node-sa-token
